/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */
export const colors = {
  light: {
    text: '#1f1e58',
    primary: '#5956fc',
    background: '#f5f5f6',
    tint: '#5956fc',
    icon: '#9f9eb7',
    error: '#ff3b30',
    success: '#34c759',
    warning: '#ff9500',
    info: '#5ac8fa',
    secondary: '#eeeeff',
    borderInput: '#cccbfe',
    textInput: '#474776',
    backgroundButtonContainer: '#fff',
    borderButtonContainer: '#fff',
    black: '#000',
    borderDrawer: '#f7f7f8',
    backgroundLogoutButton: '#ff612f14',
    borderLogoutButton: '#ff612f7a',
    colorLogoutButton: '#ff4c4c',
    backgroundCode: '#f5f5f6',
  },
  dark: {
    text: '#ecedee',
    primary: '#5956fc',
    background: '#1f1f1f',
    tint: '#151718',
    icon: '#9f9eb7',
    error: '#ff3b30',
    success: '#34c759',
    warning: '#ff9500',
    info: '#5ac8fa',
    secondary: '#eeeeff',
    borderInput: '#cccbfe',
    textInput: '#474776',
    backgroundButtonContainer: '#1f1f1f',
    borderButtonContainer: '#5956fc',
    white: '#fff',
    borderDrawer: 'transparent',
    backgroundLogoutButton: '#fffff14',
    borderLogoutButton: '#fff',
    colorLogoutButton: '#fff',
    backgroundCode: '#f5f5f6',
  },
};
