name: Notify Slack on PR Events

on:
  pull_request:
    branches: ['dev', 'stag', 'release']
    types: [opened, reopened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          ACTION="${{ github.event.action }}"
          IS_MERGED="${{ github.event.pull_request.merged }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_USER="${{ github.event.pull_request.user.login }}"
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          HEAD_BRANCH="${{ github.event.pull_request.head.ref }}"
          REPO_NAME="${{ github.repository }}"
          MERGED_BY="${{ github.event.pull_request.merged_by.login }}"
          COMPARE_URL="https://github.com/${REPO_NAME}/compare/${BASE_BRANCH}...${HEAD_BRANCH}"

          if [[ "$ACTION" == "opened" || "$ACTION" == "reopened" ]]; then
            MESSAGE="*PR ${ACTION} to \`${BASE_BRANCH}\`*\n*From:* \`${HEAD_BRANCH}\`\n*Title:* ${PR_TITLE}\n*By:* ${PR_USER}\n🔗 ${PR_URL}"

          elif [[ "$ACTION" == "closed" && "$IS_MERGED" == "true" ]]; then
            # Fetch commits in merged PR
            COMMITS=$(echo '${{ toJson(github.event.pull_request.commits) }}' | jq -r '.[]? | "• \(.id[0:8]): \(.message | split("\n")[0]) - \(.author.name)"')
            if [ -z "$COMMITS" ]; then
              COMMITS="(No commits found)"
            fi

            MESSAGE="*${MERGED_BY}* merged branch \`${HEAD_BRANCH}\` into \`${BASE_BRANCH}\` of \`${REPO_NAME}\`\n Compare changes: ${PR_URL}\n\n${COMMITS}"

          else
            echo "PR closed without merge. Skipping Slack notification."
            exit 0
          fi

          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"${MESSAGE}\"}" \
            $SLACK_WEBHOOK_URL
